
#Client configuration settings
[client]
	#The time in milliseconds to wait before polling the controller. The lower the value the better the input latency but drains the controller battery faster.
	#Range: 1 ~ 128
	controllerPollInterval = 8

	#In-game related options. These can be changed in game instead of config!
	[client.options]
		#If enabled, allows you to craft quickly when clicking an item in the recipe book
		quickCraft = true
		#If enabled, inverts the controls on the Y axis for the camera
		invertLook = false
		#If enabled, shows common actions when displaying available on the screen
		#Allowed Values: ALL, MINIMAL, NONE
		showActions = "MINIMAL"
		#If enabled, the player will render in the top left corner likes Bedrock Edition
		renderMiniPlayer = true
		#The speed which the cursor or virtual mouse moves around the screen
		#Range: 0.0 ~ 50.0
		mouseSpeed = 15.0
		#The image to use for the cursor. This only applies if virtual mouse is enabled!
		#Allowed Values: LIGHT, DARK, CONSOLE, LEGACY_LIGHT, LEGACY_DARK
		cursorType = "LIGHT"
		#The speed which the camera turns in game
		#Range: 0.0 ~ 100.0
		rotationSpeed = 25.0
		#The distance you have to move the thumbstick before it's input is registered. This fixes drifting as some thumbsticks don't center to zero.
		#Range: 0.0 ~ 1.0
		deadZone = 0.15
		#The controller icons to use in game to display actions
		#Allowed Values: DEFAULT, PLAYSTATION_4, PLAYSTATION_3, XBOX_ONE, XBOX_360, SWITCH_JOYCONS, SWITCH_CONTROLLER, GAMECUBE, STEAM
		controllerIcons = "DEFAULT"
		#If enabled, controller will be automatically selected on start up or when plugged in
		autoSelect = true
		#If enabled, the game will use a virtual cursor instead of the real cursor. This must be turned on to be able to run multiple instances!
		virtualMouse = true
		#The behaviour to use for sneaking. Toggle means to press once to sneak then press again to stand again. Hold means you must hold the sneak button and releasing will make the player stand again.
		#Allowed Values: TOGGLE, HOLD
		sneakMode = "TOGGLE"
		#If enabled, plays a pop sound when you navigate in inventories, menus or scrolling the radial menu
		uiSounds = true
		#If enabled, some actions will cause the controller to vibrate
		forceFeedback = true
		#If enabled, hotbar will render closer to the center of the screen like on console.
		consoleHotbar = false
		#The thumbstick to use when scrolling items in the radial menu
		#Allowed Values: LEFT, RIGHT
		radialThumbstick = "RIGHT"
		#The scale of the mouse speed when hovering a widget or item slot
		#Range: 0.05 ~ 1.0
		hoverModifier = 0.6
		#The thumbstick that controls moving the cursor
		#Allowed Values: LEFT, RIGHT
		cursorThumbstick = "LEFT"

