
["Bamboo Grove World Generation"]
	#Spawn rice paddies in the Bamboo Grove
	spawnRicePaddies = true
	#Spawn Bamboo Groves in Overworld
	spawnBambooGroves = true
	#Bamboo Grove rarity - Higher equals more frequent
	#Range: 0 ~ 30
	bambooGroveRarity = 5
	#Spawn Cherry blossom center pieces inside the Bamboo Grove
	spawnCherryBlossomStructures = true
	#Spawn Jade in the Bamboo Grove
	spawnJade = true
	#Spawn giant Torii gates inside the Bamboo Grove
	spawnToriiGates = true

["Vanilla Tweaks"]
	#Spawn Amethysdt in the Overworld
	spawnAmethyst = true
	#Size of Marble vein generated all over the Overworld
	#Range: 0 ~ 64
	marbleVeinSizeInOverworld = 20
	#Sets the max stack size for cawl
	#Range: 1 ~ 64
	cawlStackSize = 16
	#Chance of spawning Marble in the Overworld
	#Range: 0 ~ 100
	marbleChanceInOverworld = 10
	#Size of Slate vein in the Snowdonia
	#Range: 0 ~ 64
	slateVeinSizeInSnowdonia = 44
	#Chance of spawning Slate in theSnowdonia
	#Range: 0 ~ 100
	slateChanceInSnowdonia = 40
	#Size of Marble vein in the Forested Mountain biome
	#Range: 0 ~ 64
	marbleVeinSizeInForestedMountains = 64
	#Allow noctilucas to spawn naturally in the world
	spawnNoctilucas = true
	#Spawn Snowdonia biome in Overworld
	spawnSnowdonia = true
	#Chance of spawning Basalt in the Overworld
	#Range: 0 ~ 100
	basaltChanceInOverworld = 10
	#Spawn slimey caves in Overworld
	spawnSpawnChunkCaves = true
	#Allow Horses to swim - (They wont buck you off if in deep water)
	swimmingHorse = true
	#Spawn Slate in Snowdonia (has a much higher ratio)
	spawnSlateInSnowdonia = true
	#Spawn Temple Ruins in the Forested Mountains
	spawnTempleRuins = true
	#Snowdonia rarity - Higher equals more frequent
	#Range: 0 ~ 100
	snowdoniaRarity = 2
	#Forested Mountain rarity - Higher equals more frequent
	#Range: 0 ~ 100
	forestedMountainRarity = 5
	#Chance of spawning Marble in the Forested Mountain biome
	#Range: 0 ~ 100
	marbleChanceInForestedMountains = 60
	#Spawn extra coal ore in Snowdonia
	spawnExtraCoalOre = true
	#Spawn Marble in Forested Mountain (has a much higher ratio)
	spawnMarbleInForestedMountains = true
	#Size of Basalt vein generated all over the Overworld
	#Range: 0 ~ 64
	basaltVeinSizeInOverworld = 33
	#Spawn Ruby in the Forested Mountains
	spawnRuby = true
	#Spawn Marble in Overworld
	spawnMarbleInOverworld = true
	#Spawn extra gold ore in Snowdonia
	spawnExtraGoldOre = true
	#Spawn Basalt in Overworld
	spawnBasaltInOverworld = true
	#Spawn Forested Mountains in Overworld
	spawnForestedMountain = true

