
#General configuration settings
[general]
	scaledProjectiles = true
	scaledReach = true
	scaledHealth = true
	scaledExplosions = true
	accurateNetherPortals = true
	scaledDefense = true
	scaledFallDamage = true
	scaledAttack = true
	scaledItemDrops = true
	keepAllScalesOnRespawn = false
	scaledMotion = true
	enableCommands = true
	scalesKeptOnRespawn = []
	enableDebugCommands = false

